### ISSUE TITLE
Birads 3 Categories 

### ISSUE THREAD

**Issue by Emirbz** [nyukat/BIRADS_classifier#13]
Hello , i'm using this repository for my school project 'Breast cancer classification using mammoram pictures'  the project is working perfectly
my question is why it shows only 3 birads categories while birads got 7 categories ?
Thank you for reading my question 👍

**Comment by kjgeras** [comment]
Hi Amir,

This is because we are only considering the three BI-RADS used in screening mammography (0, 1, 2). In later stages of the diagnostic pipeline, a patient can be assigned other BI-RADS. What it means is that, if you want to use our models, you should do one of two things:

1. Change your prediction task by mapping all BI-RADS categories into three BI-RADS categories. I suggest to follow the way we describe here: https://cs.nyu.edu/~kgeras/reports/datav1.0.pdf (i.e., 0->0, 1->1, 2->2, 3->2, 4a->0, 4b->0, 4c->0, 5->0).
2. Drop the last layer of our network and put a new one with however many outputs you want to predict.

Please also check this repository: https://github.com/nyukat/breast_cancer_classifier
It contains much stronger models than this one.

**Comment by Emirbz** [comment]
What does each Number stand for ?
0  probability of what ? same for 1 and 2 💃

**Comment by kjgeras** [comment]
These are different categories. 

BI-RADS 0: "incomplete, needs additional imaging"
BI-RADS 1: "normal"
BI-RADS 2: "bening"

You can read more about these for example here: https://breast-cancer.ca/bi-rads/

**Comment by Emirbz** [comment]
thanks for your quick response
So to have the others categories : 
0- incomplete
1-negative
2-benign findings
3-probably benign
4-suspicious abnormality
5-highly suspicious of malignancy
6-known biopsy with proven malignancy
i have to use the other project (breast_cancer_classifier)? 
because i need the malignancy probability

**Comment by kjgeras** [comment]
Not exactly. In order to explain this, I would basically need to write a few pages. Please read the website that I gave you a link to first, then this paper:
https://arxiv.org/pdf/1703.07047.pdf
and this paper
https://arxiv.org/pdf/1903.08297.pdf
and everything will be clear.
